### ISSUE TITLE
[dados] br_camara_atividade_legislativa

### ISSUE THREAD

**Issue by jpdonasolo** [basedosdados/mais#1332]
**Metadados da base**

1. Descrição: Lista com identificadores e informações diversas sobre as reuniões, sessões, audiências, seminários e outros eventos realizados pelos diversos órgãos legislativos da Câmara, inclusive eventos já agendados e não ocorridos. 

2. Qual o nome do conjunto? `br_camara_atividade_legislativa`

3. Qual o nome da(s) tabela(s)? `eventos`

4. Fonte original dos dados: [link](https://dadosabertos.camara.leg.br/swagger/api.html#staticfile)

5. Cobertura espacial: Brasil

6. Cobertura temporal: de 1991 a 2022

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [x] Criar tabela dicionário, se necessário.
- [x] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by jpdonasolo** [comment]
Não estou conseguindo fazer upload para o Google Cloud... Primeiro, tento usar o comando como está no site:

```
$ basedosdados table create br_camara_atividade_legislativa evento --path output/evento.csv --force_dataset False --if_table_exists raise --if_storage_data_exists raise --if_table_config_exists raise --columns_config_url https://docs.google.com/spreadsheets/d/1mpXq-XEPOjI22BzJLgiGGMBFE47ChOdxjRhoT-13hHk/edit#gid=0
```
o que retorna o erro
```
Usage: basedosdados table create [OPTIONS] DATASET_ID TABLE_ID
Try 'basedosdados table create --help' for help.

Error: No such option: --columns_config_url (Possible options: --columns_config_url_or_path, --job_config_params)
```

Mudando o último argumento para `columns_config_url_or_path`:

```
$ basedosdados table create br_camara_atividade_legislativa evento --path output/evento.csv --force_dataset False --if_table_exists raise --if_storage_data_exists raise --if_table_config_exists raise --columns_config_url_or_path https://docs.google.com/spreadsheets/d/1mpXq-XEPOjI22BzJLgiGGMBFE47ChOdxjRhoT-13hHk/edit#gid=0

Traceback (most recent call last):
  File "/home/joao/Documents/br_camara_atividade_legislativa/bin/basedosdados", line 8, in <module>
    sys.exit(cli())
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/joao/Documents/br_camara_atividade_legislativa/lib/python3.10/site-packages/basedosdados/cli/cli.py", line 340, in create_table
    Table(table_id=table_id, dataset_id=dataset_id, **ctx.obj).create(
TypeError: Table.create() got an unexpected keyword argument 'job_config_params'
```

Será que foi algum erro na configuração do módulo do basedosdados? Ou então na criação do projeto no google cloud? Segui o tutorial como no site, criei o projeto, o bucket, baixei e movi a chave...

**Comment by mfagundes** [comment]
O erro estava no pacote Python. Por favor, atualize seu pacote para a versão `1.6.6` e, se possível, nos informe se deu tudo certo, ok?

Muito obrigado pela sua ajuda.

**Comment by jpdonasolo** [comment]
Os erros mudaram, então agora deve ser eu fazendo algo errado hahah se não conseguir resolver aqui, eu aviso. Obrigado

**Comment by jpdonasolo** [comment]
Ainda não estou conseguindo fazer o upload. Tentei fazer algumas mudanças de path e nomes, mas não funcionou.

A estrutura de pastas está assim:

```
base_dos_dados (venv)
├── bases
└── br_camara_atividade_legislativa
    ├── code
    │   ├── clean_data.py
    │   └── download_data.py
    ├── dataset_config.yaml
    ├── evento
    │   ├── publish.sql
    │   ├── schema-staging.json
    │   └── table_config.yaml
    ├── extra
    │   ├── architecture
    │   ├── auxiliary_files
    │   └── dicionario.csv
    ├── input
    │   ├── eventos_1991.csv
    │   ├── ...
    │   └── eventos_2022.csv
    ├── output
    │   └── evento.csv
    └── tmp
```
Na google cloud, tenho o projeto `basedosdados` e o bucket `br_camara_atividade_legislativa`.

```python
>>> import basedosdados as bd
>>> tb = bd.Table(dataset_id="br_camara_atividade_legislativa", table_id="evento")
>>> tb.create(
...     path="bases/br_camara_atividade_legislativa/output",
...     force_dataset=False,
...     if_table_exists='replace',
...     if_storage_data_exists='replace',
...     if_table_config_exists='replace',
... )
Uploading files: 100%|██████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.04s/it]
2022-09-30 15:36:29.967 | SUCCESS  | basedosdados.upload.storage:upload:232 -  File evento.csv_['staging'] was uploaded!
2022-09-30 15:36:33.171 | SUCCESS  | basedosdados.upload.metadata:create:343 -  Metadata evento was created!
2022-09-30 15:36:34.781 | INFO     | basedosdados.upload.table:delete:830 -  Table evento_staging was deleted!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/basedosdados/upload/table.py", line 708, in create
    self.client["bigquery_staging"].create_table(table)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 726, in create_table
    api_response = self._call_api(
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 760, in _call_api
    return call()
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/basedosdados/datasets/br_camara_atividade_legislativa_staging/tables?prettyPrint=false: Not found: Dataset basedosdados:br_camara_atividade_legislativa_staging
```

Tentei na linha de comando, e o erro foi exatamente o mesmo. Usei `replace` ao invés de `raise` porque já tinha tentado o upload uma vez, os erros tinham dado outros mas as tabelas não foram excluídas, ou algo assim.

```
$ basedosdados table create br_camara_atividade_legislativa evento --path bases/br_camara_atividade_legislativa/output/ --force_dataset False --if_table_exists replace --if_storage_data_exists replace --if_table_config_exists replace --columns_config_url_or_path https://docs.google.com/spreadsheets/d/1mpXq-XEPOjI22BzJLgiGGMBFE47ChOdxjRhoT-13hHk/edit#gid=0
```

```python
Uploading files: 100%|██████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.32s/it]
2022-09-30 15:51:50.656 | SUCCESS  | basedosdados.upload.storage:upload:232 -  File evento.csv_['staging'] was uploaded!
2022-09-30 15:51:53.710 | SUCCESS  | basedosdados.upload.metadata:create:343 -  Metadata evento was created!
2022-09-30 15:51:56.695 | INFO     | basedosdados.upload.table:delete:830 -  Table evento_staging was deleted!
Traceback (most recent call last):
  File "/home/joao/Documents/base_dos_dados/bin/basedosdados", line 8, in <module>
    sys.exit(cli())
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/basedosdados/cli/cli.py", line 336, in create_table
    Table(table_id=table_id, dataset_id=dataset_id, **ctx.obj).create(
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/basedosdados/upload/table.py", line 708, in create
    self.client["bigquery_staging"].create_table(table)
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 726, in create_table
    api_response = self._call_api(
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 760, in _call_api
    return call()
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/joao/Documents/base_dos_dados/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/basedosdados/datasets/br_camara_atividade_legislativa_staging/tables?prettyPrint=false: Not found: Dataset basedosdados:br_camara_atividade_legislativa_staging
```
E a tabela chegou a ser criada no google cloud (o caminho tá super esquisito, por isso acho que fiz besteira com os paths)

![Screenshot from 2022-09-30 15-54-19](https://user-images.githubusercontent.com/71014993/193337863-cd2e096d-89d0-46e4-ac7c-bb0949a21d11.png)

**Comment by mfagundes** [comment]
Tente, por favor, rodar com o `force_dataset=True`. Vou dar uma estudada no que pode estar acontecendo com esses seus dados e atualizo aqui.

**Comment by filipemsc** [comment]
@jpdonasolo Acho que o erro está no fato de que provavelmente você forneceu o **nome do projeto** em vez do **ID do projeto** para o pacote. Acho que é impossível você ter um projeto com o id `basedosdados`, pois o ID do projeto no Google Cloud é único, e esse nome já está é possuído pela organização. Eu faria o seguinte: 

1) Cheque qual o **ID do seu projeto**. Para isso, vá em: https://console.cloud.google.com/ e clique no nome do projeto aparecendo no canto superior esquerdo. Veja se ele corresponde à `basedosdados`.
2) Procure o arquivo `config.toml` do pacote `basedosdados`. Ele deve estar na pasta ".basedosdados/", que aqui no meu pc fica na minha pasta raiz de usuário.
3) Veja qual o "name" do seu `gcloud-projects.staging` e `gcloud-projects.prod`. Eles devem ser iguais ao ID do seu projeto, se não forem, altere para que eles sejam equivalentes.

Se quiser a gente pode ver juntos depois no Discord!

**Comment by jpdonasolo** [comment]
@filipemsc A ID estava errada mesmo, alterei no `config.toml`, e também usei o `force_dataset=True`. 

O erro é o seguinte agora:
```python
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/basedosdados-364117/datasets/br_camara_atividade_legislativa_staging/tables?prettyPrint=false: Field missing name
```

Meu `config.toml` está assim, depois das alterações:

```
# Where to save all metadata data, such as Dataset and Table config files.
# We reccomend this path to be the same as the github repo clone
metadata_path = "/home/joao/Documents/base_dos_dados/bases"

# What is the bucket that you are saving all the data? It should be 
# an unique name.
bucket_name = "br_camara_atividade_legislativa"

# Where the templates to generate configs and descriptions sit
templates_path = "/home/joao/.basedosdados/templates"

[gcloud-projects]

    [gcloud-projects.staging]
        name = "basedosdados-364117"
        credentials_path = "/home/joao/.basedosdados/credentials/staging.json"

    [gcloud-projects.prod]
        name = "basedosdados-364117"
        credentials_path = "/home/joao/.basedosdados/credentials/prod.json"

# Data about you to auto-fill config
# TODO: issue 20
[user]
name = "Joao Donasolo"
email = "jpdonasolo@gmail.com"
website = ""

[ckan]
url = ""
api_key = ""
```

**Comment by filipemsc** [comment]
@jpdonasolo já tentou rodar sem o argumento "columns_config_url_or_path"?

**Comment by mfagundes** [comment]
Não está relacionado a esse erro, porém observei que o seu `config.toml` deveria ter, em  `bucket_name` um nome mais genérico (recomendo colocar o mesmo do seu projeto, que é `basedosdados-364117`. O bucket de cada `dataset` (nesse caso específico, o `br_camara_atividade_legislativa` será criado dentro dele (dentro de outro bucket chamado `staging`) onde seus dados serão salvos.

**Comment by jpdonasolo** [comment]
@filipemsc Funcionou!! @mfagundes entendi. Vou mudar isso. Obrigado aos dois

**Comment by filipemsc** [comment]
> @filipemsc Funcionou!! @mfagundes entendi. Vou mudar isso. Obrigado aos dois

Agora é aprender a preencher metadados hehe :)
